
import Charts from "./Charts";
import "./Dashboard.css";
import {
  FaMoon,
  FaBrain,
  FaSmile,
  FaChartLine,
  FaBed,
  FaMobileAlt,
  FaRunning,
  FaTint,
  FaArrowRight,
} from "react-icons/fa";

export default function Dashboard({ result }) {
  if (!result) return null;

  const sleepScore = Math.round(result.Confidence * 100);

  return (
    <section className="dashboard-section" id="dashboard">
      {/* HEADER */}
      <div className="dashboard-header">
        <div>
          <h1>Welcome back 👋</h1>
          <p>Here's your AI-powered wellness summary generated by Somnia AI.</p>
        </div>
      </div>

      {/* TOP CARDS */}
      <div className="summary-grid">
        <div className="summary-card dash-glass">
          <div className="summary-icon blue">
            <FaMoon />
          </div>
          <h4>Sleep Score</h4>
          <h2>{sleepScore}/100</h2>
          <div className="progress">
            <div className="progress-fill" style={{ width: `${sleepScore}%` }}></div>
          </div>
        </div>

        <div className="summary-card dash-glass">
          <div className="summary-icon purple">
            <FaBrain />
          </div>
          <h4>Stress Level</h4>
          <h2>{result.Predicted_Stress_Level}</h2>
          <div className="progress">
            <div className="progress-fill purple-fill" style={{ width: `${sleepScore}%` }}></div>
          </div>
        </div>

        <div className="summary-card dash-glass">
          <div className="summary-icon green">
            <FaSmile />
          </div>
          <h4>Mood</h4>
          <h2>{sleepScore > 70 ? "Balanced" : "Needs Care"}</h2>
          <div className="progress">
            <div className="progress-fill green-fill" style={{ width: `${sleepScore}%` }}></div>
          </div>
        </div>

        <div className="summary-card dash-glass">
          <div className="summary-icon cyan">
            <FaChartLine />
          </div>
          <h4>Confidence</h4>
          <h2>{sleepScore}%</h2>
          <div className="progress">
            <div className="progress-fill cyan-fill" style={{ width: `${sleepScore}%` }}></div>
          </div>
        </div>
      </div>

      {/* AI RECOMMENDATIONS */}
      <div className="recommendation-card dash-glass">
        <div className="recommendation-header">
          <div>
            <h2>
              <FaBrain />
              AI Recommendations
            </h2>
            <p>Personalized suggestions generated by Somnia AI.</p>
          </div>
          <button>
            View All
            <FaArrowRight />
          </button>
        </div>

        <div className="recommendation-grid">
          {result.Advice.map((item, index) => {
            const icons = [<FaBed />, <FaMobileAlt />, <FaRunning />, <FaTint />];
            return (
              <div className="recommend-box" key={index}>
                <div className="recommend-icon">{icons[index % icons.length]}</div>
                <div>
                  <h3>Recommendation {index + 1}</h3>
                  <p>{item}</p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
      <Charts />
    </section>
  );
}
